[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ccp4x"
dynamic = ["version"]
authors = [{ name = "Paul Bond", email = "paul.bond@york.ac.uk" }]
maintainers = [{ name = "Paul Bond", email = "paul.bond@york.ac.uk" }]
description = "Interface for CCP4 software"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["CCP4", "X-ray", "Crystallography", "MX", "Interface"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Private :: Do Not Upload",
]
dependencies = [
    "django-cors-headers",
    "django-filter",
    "django",
    "djangorestframework",
    "gemmi",
    "pytest",
    "requests-cache",
    "requests",
]
requires-python = ">=3.9.8"

[project.gui-scripts]
ccp4x = "ccp4x.__main__:main"

[project.urls]
Source = "https://github.com/paulsbond/ccp4x"
Issues = "https://github.com/paulsbond/ccp4x/issues"

[tool.setuptools.dynamic]
version = { attr = "ccp4x.__version__" }
