name: Electron Multiplatform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Rebuild native modules for Electron
        run: npx @electron/rebuild
        working-directory: ./client

      - name: Build app
        run: npm run build
        working-directory: client

      - name: Package macOS app (dmg)
        run: npm run package-mac
        working-directory: client

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-dmg
          path: client/dist/*.dmg

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Build app
        run: npm run build
        working-directory: client

      - name: Package Windows app (nsis & portable)
        run: npm run package-win
        working-directory: client

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            client/dist/*.exe
            client/dist/*.portable.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Build app
        run: npm run build
        working-directory: client

      - name: Package Linux x64 and arm64 AppImages
        run: npm run package-linux-all
        working-directory: client

      - name: Upload Linux AppImage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimages
          path: client/dist/*.AppImage
